version: '3'

services:
    ros_noetic_dev:
        image: ros_noetic_dev
        build: .
        container_name: ros_noetic_dev
        environment:
            - DISPLAY=novnc:0.0
        volumes:
            - ./homework_ws/src:/root/noetic-dev/ros/homework_ws/src
        stdin_open: true # docker run -i
        tty: true # docker run -t
        depends_on:
            - novnc
        networks:
            - x11
        command: /bin/bash -c 'source /opt/ros/noetic/setup.bash && (roscore &)'
    novnc:
        image: theasp/novnc:latest
        environment:
            # Adjust to your screen size
            - DISPLAY_WIDTH=1600
            - DISPLAY_HEIGHT=968
            - RUN_XTERM=no
        ports:
            - "8080:8080"
        networks:
            - x11
networks:
    x11:
