version: '3'

services:
    rosmaster:
        image: ros_test
        build: .
        container_name: rosmaster
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - .:/root/noetic-dev/ros
        network_mode: host
        command: /bin/bash -c 'source /opt/ros/noetic/setup.bash && (roscore &) ; bash'
        stdin_open: true # docker run -i
        tty: true # docker run -t
