version: '3'

services:
    ros_noetic_dev:
        image: ros_docker_x11
        build: .
        container_name: ros_docker_x11
        # ENV variables to tell Docker which display to forward to
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
        # Mount the X11 socket
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - .:/root/noetic-dev/ros
        network_mode: host
        command: /bin/bash -c 'source /opt/ros/noetic/setup.bash && (roscore &) ; bash'
        stdin_open: true # docker run -i
        tty: true # docker run -t
