#!/usr/bin/env python

# Copyright (c) 2019, The Personal Robotics Lab, The MuSHR Team, The Contributors of MuSHR
# License: BSD 3-Clause. See LICENSE.md file in root directory.

import rospy
from geometry_msgs.msg import PoseStamped, PointStamped


def point_clicked_cb(msg):
    as_pose = PoseStamped(header=msg.header)
    as_pose.pose.position = msg.point
    as_pose.pose.orientation.w = 1
    pub.publish(as_pose)


if __name__ == "__main__":
    rospy.init_node("point_clicked_to_reposition")

    sub = rospy.Subscriber("/clicked_point", PointStamped, point_clicked_cb, queue_size=1)
    pub = rospy.Publisher("~reposition", PoseStamped, queue_size=1)

    rospy.spin()
