#!/usr/bin/env python

# Copyright (c) 2019, The Personal Robotics Lab, The MuSHR Team, The Contributors of MuSHR
# License: BSD 3-Clause. See LICENSE.md file in root directory.

import os
import signal
import atexit
import rospy
from threading import Thread
from mushr_sim.keyboard_teleop import KeyboardTeleop


class TeleopThread(Thread):
    def __init__(self):
        super(TeleopThread, self).__init__()

    def run(self):
        # Temporarily disable keyboard repeats
        os.system("xset r off")
        self.teleop = KeyboardTeleop()
        self.teleop.root.mainloop()


def main():
    rospy.init_node("keyboard_teleop", disable_signals=True)

    # Reenable key repeats on exit
    atexit.register(lambda: os.system("xset r on"))

    teleop_thread = TeleopThread()
    signal.signal(signal.SIGINT, lambda x, y: teleop_thread.teleop.shutdown())
    teleop_thread.start()
    print("Press Q to quit")


if __name__ == "__main__":
    main()
