arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - waist
    - shoulder
    - elbow
    - forearm_roll
    - wrist_angle
    - wrist_rotate
  constraints:
    goal_time: 1
    stopped_velocity_tolerance: 0.02

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_finger
